export const START_MEMORY_GAME = 'START_MEMORY_GAME';
export const FLIP_TILE = 'FLIP_TILE';
export const MATCH_CHECK= 'MATCH_CHECK';
export const TOGGLE_IS_WAITING = 'TOGGLE_IS_WAITING';
export const INCREMENT_TRIES = 'INCREMENT_TRIES';
export const DB_USER_SET = 'DB_USER_SET';
export const UPDATE_LEVELS = 'UPDATE_LEVELS';
export const RESET_LEVELS = 'RESET_LEVELS';