export const START_MULTI_CHOICE_GAME = 'START_MULTI_CHOICE_GAME';
export const ON_ANSWER_CLICK = 'ON_ANSWER_CLICK';
export const RESET_LEVELS = 'RESET_LEVELS';
/*export const SET_DEFAULT_OSCILLATOR_NODE = 'SET_DEFAULT_OSCILLATOR_NODE';*/
