export const START_MULTI_CHOICE_GAME = 'START_MULTI_CHOICE_GAME';
export const ON_ANSWER_CLICK = 'ON_ANSWER_CLICK';
export const RESET_LEVELS = 'RESET_LEVELS';
export const UPDATE_LEVELS = 'UPDATE_LEVELS';
export const DB_USER_SET = 'DB_USER_SET';
/*export const SET_DEFAULT_OSCILLATOR_NODE = 'SET_DEFAULT_OSCILLATOR_NODE';*/
