export const START_GAME = 'START_GAME';
export const FINISH_GAME = 'FINISH_GAME';
export const SET_DEST_OSCILLATOR_NODE = 'SET_DEST_OSCILLATOR_NODE';
export const SET_KNOB_OSCILLATOR_NODE = 'SET_KNOB_OSCILLATOR_NODE';