export const START_SORT_GAME = 'START_SORT_GAME';
export const FINISH_SORT_GAME = 'FINISH_SORT_GAME';
export const SORT_END = 'SORT_END';
export const HANDLE_SORT_COMPONENT_CLICK = 'HANDLE_SORT_COMPONENT_CLICK';
export const SET_DEFAULT_OSCILLATOR_NODE = 'SET_DEFAULT_OSCILLATOR_NODE';