export const START_PITCH_EQUALIZER_GAME = 'START_PITCH_EQUALIZER_GAME';
export const FINISH_PITCH_EQUALIZER_GAME = 'FINISH_PITCH_EQUALIZER_GAME';
export const SET_DEST_PITCH_EQUALIZER_OSCILLATOR_NODE = 'SET_DEST_PITCH_EQUALIZER_OSCILLATOR_NODE';
export const SET_KNOB_PITCH_EQUALIZER_OSCILLATOR_NODE = 'SET_KNOB_PITCH_EQUALIZER_OSCILLATOR_NODE';
export const ON_DEST_PITCH_EQUALIZER_BUTTON_CLICK = 'ON_DEST_PITCH_EQUALIZER_BUTTON_CLICK';
export const ON_PITCH_EQUALIZER_KNOB_BUTTON_CLICK = 'ON_PITCH_EQUALIZER_KNOB_BUTTON_CLICK';
export const ON_PITCH_EQUALIZER_TRY_AGAIN = 'ON_PITCH_EQUALIZER_TRY_AGAIN';